//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octokit.CodeAnalysis {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Octokit.CodeAnalysis.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analyzer has verified the `uri` defined in the method does not match the `uri` defined in the [Endpoint] attribute..
        /// </summary>
        internal static string EndpointMismatchAnalyzerDescription {
            get {
                return ResourceManager.GetString("EndpointMismatchAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; declares it consumes &apos;{1}&apos; but actually uses &apos;{2}&apos;.
        /// </summary>
        internal static string EndpointMismatchAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("EndpointMismatchAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implemented endpoint does not match declared endpoint.
        /// </summary>
        internal static string EndpointMismatchAnalyzerTitle {
            get {
                return ResourceManager.GetString("EndpointMismatchAnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditable client methods should assign the `uri` in the method, so analyzers can verify it matches the documented endpoint..
        /// </summary>
        internal static string UnableToVerifyEndpointAnalyzerDescription {
            get {
                return ResourceManager.GetString("UnableToVerifyEndpointAnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; does not assign a local `uri` to audit..
        /// </summary>
        internal static string UnableToVerifyEndpointAnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("UnableToVerifyEndpointAnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to audit client method.
        /// </summary>
        internal static string UnableToVerifyEndpointAnalyzerTitle {
            get {
                return ResourceManager.GetString("UnableToVerifyEndpointAnalyzerTitle", resourceCulture);
            }
        }
    }
}
